{
  "name": "SERVER-CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "jobs": {
    "linter": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v2",
          "with": {
            "asdf-system": "openrpc-server",
            "asdf-version": "3.3.5.1"
          }
        },
        {
          "name": "Change dist to Ultralisp",
          "run": "echo 'dist ultralisp http://dist.ultralisp.org' > qlfile",
          "shell": "bash"
        },
        {
          "name": "Update Qlot",
          "run": "qlot update || qlot update",
          "shell": "bash"
        },
        {
          "name": "Install SBLint wrapper",
          "run": "qlot exec ros install 40ants-linter",
          "shell": "bash"
        },
        {
          "name": "Run Linter",
          "run": "qlot exec 40ants-linter --system \"openrpc-server\"",
          "shell": "bash"
        }
      ]
    },
    "run-tests": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "ultralisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v2",
          "with": {
            "asdf-system": "openrpc-server",
            "asdf-version": "3.3.5.1"
          }
        },
        {
          "name": "Run Tests",
          "uses": "40ants/run-tests@v2",
          "with": {
            "asdf-system": "openrpc-server",
            "coveralls-token": "${{ secrets.github_token }}"
          }
        }
      ]
    }
  }
}